### ISSUE TITLE
Angular 13: Uncaught ReferenceError: SRS_CLASS is not defined

### ISSUE THREAD

**Issue by JanHanckel** [DanielJDufour/spatial-reference-system#5] opened 2023-07-24 13:52 UTC
Hi,

I just migrated from Angular 12 to 13 and now I'm gettig this error on loading the side.

index.js:175 Uncaught ReferenceError: SRS_CLASS is not defined

Any idea how to fix this?

**Comment by DanielJDufour** [comment] 2023-07-24 23:45
Hello, thank you for raising this issue!  I'm sorry for the inconvenience this is causing.  I tried to replicate this issue and was unsuccessful.  I don't use angular much these days, so could use your assistance!  Would you be able to share a test that reproduces this error or share excerpts of your relevant code?  Thank you!

I have a hunch that the issue is this line: https://github.com/DanielJDufour/spatial-reference-system/blob/main/index.js#L175, but a test could help confirm it :-)

**Comment by JanHanckel** [comment] 2023-07-25 06:51
Hi, i have no test, but what fixed it for me:
changed line 175 to

`const SRS_CLASS = SRS;`

**Comment by DanielJDufour** [comment] 2023-07-25 09:49
Awesome! Would you like to submit a PR?

**Comment by DanielJDufour** [comment] 2023-07-27 23:28
This should be fixed by the new version just published: v0.5.2

Please reopen if you continue to have problems.  Happy to help! :-)

**Closed as completed by DanielJDufour** 2023-07-27 23:28 UTC
